---
version: '3'
services:

  mysql:
    image: mysql:8.0
    labels:
      de.nt.cloud.group: ntpartner
      de.nt.cloud.name: ntpartner-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ntpartner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    volumes:
      - /var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.6-management
    labels:
      de.nt.cloud.group: ntpartner
      de.nt.cloud.name: ntpartner-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mquser
      RABBITMQ_DEFAULT_PASS: mquser
      RABBITMQ_DEFAULT_VHOST: ntpartner
    volumes:
      - /var/lib/rabbitmq

networks:
  default:
...